config/routes.rb
Rails.application.routes.draw do
  devise_for :user
  resources :users, only: [:show, :edit, :update]
  root to: "animals#index"
  resources :animals
end

app/models/animal.rb
class Animal < ApplicationRecord
  with_options presence:true do
    validates :nickname
    validates :sex
    validates :vaccine
    validates :sterilization
    validates :character
    validates :reason
    validates :transfer_cost
    validates :transfer_terms
    validates :image

    with_options numericality: { other_than: 0 } do
      validates :old_year_id, numericality: { other_than: 0 }
      validates :old_month_id, numericality: { other_than: 0 }
      validates :prefecture_id, numericality: { other_than: 0 }
    end
  end
  belongs_to :user
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :old_year
  belongs_to :old_month
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/old.rb
class Old < ActiveHash::Base

  self.data = [
              {id: 0, name: '--'}, {id: 1, name: '10代'}, {id: 2, name: '20代'},
              {id: 3, name: '30代'}, {id: 4, name: '40代'}, {id: 5, name: '50代'},
              {id: 6, name: '60代'}, {id: 7, name: '70代'}, {id: 8, name: '80代'},
              {id: 9, name: '90代'}
              ]

  include ActiveHash::Associations
  has_many :users
  has_many :animals
end

app/models/old_month.rb
class OldMonth < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '1ヶ月'}, {id: 2, name: '2ヶ月'},
    {id: 3, name: '3ヶ月'}, {id: 4, name: '4ヶ月'}, {id: 5, name: '5ヶ月'},
    {id: 6, name: '6ヶ月'}, {id: 7, name: '7ヶ月'}, {id: 8, name: '8ヶ月'},
    {id: 9, name: '9ヶ月'}, {id: 10, name: '10ヶ月'}, {id: 11, name: '11ヶ月'}
    ]

  include ActiveHash::Associations
  has_many :animals
end

app/models/old_year.rb
class OldYear < ActiveHash::Base
  self.data = [
    {id: 0, name: '--'}, {id: 1, name: '0才'}, {id: 2, name: '1才'},
    {id: 3, name: '2才'}, {id: 4, name: '3才'}, {id: 5, name: '4才'},
    {id: 6, name: '5才'}, {id: 7, name: '6才'}, {id: 8, name: '7才'},
    {id: 9, name: '8才'}, {id: 10, name: '9才'}, {id: 11, name: '10才'}
    ]

  include ActiveHash::Associations
  has_many :animals
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base

  self.data = [
                {id: 0, name: '--'}, {id: 1, name: '北海道'}, {id: 2, name: '青森県'},
                {id: 3, name: '岩手県'}, {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'},
                {id: 6, name: '山形県'}, {id: 7, name: '福島県'}, {id: 8, name: '茨城県'},
                {id: 9, name: '栃木県'}, {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'},
                {id: 12, name: '千葉県'}, {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'},
                {id: 15, name: '新潟県'}, {id: 16, name: '富山県'}, {id: 17, name: '石川県'},
                {id: 18, name: '福井県'}, {id: 19, name: '山梨県'}, {id: 20, name: '長野県'},
                {id: 21, name: '岐阜県'}, {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'},
                {id: 24, name: '三重県'}, {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'},
                {id: 27, name: '大阪府'}, {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'},
                {id: 30, name: '和歌山県'}, {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'},
                {id: 33, name: '岡山県'}, {id: 34, name: '広島県'}, {id: 35, name: '山口県'},
                {id: 36, name: '徳島県'}, {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'},
                {id: 39, name: '高知県'}, {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'},
                {id: 42, name: '長崎県'}, {id: 43, name: '熊本県'}, {id: 44, name: '大分県'},
                {id: 45, name: '宮崎県'}, {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
              ]

  include ActiveHash::Associations
  has_many :users
  has_many :animals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         with_options presence:true do
          validates :nickname
          validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を入力してください" }
          validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: "を入力してください" }
          validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "を入力してください" }
          validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: "を入力してください" }
          validates :prefecture_id, numericality: { other_than: 0, message: "を選択してください" }
          validates :city
          validates :old_id, numericality: { other_than: 0, message: "を選択してください" }
          validates :gender
         end
         has_one_attached :image
         has_many :animals
         extend ActiveHash::Associations::ActiveRecordExtensions
         belongs_to :old
         belongs_to :prefecture
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :animal_find, only: [:show, :edit, :destroy]
  def index
    @animals = Animal.includes(:user)
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    if @animal.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  # else時エラーメッセージ出力必要あり
  def update
    animal = Animal.find(params[:id])
    if animal.update(animal_params)
      redirect_to animal_path
    else
      render :edit
    end
  end

  def destroy
    @animal.destroy
    redirect_to root_path
  end

  private
  def animal_find
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:nickname, :sex, :old_year_id, :old_month_id, :vaccine, :sterilization, :character, :reason, :prefecture_id, :transfer_cost, :transfer_terms, :image).merge(user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :prefecture_id, :city, :old_id, :gender, :image])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :user_find, only: [:show, :edit, :update]
  before_action :move_to_index, only: [:edit]

  def show
    @animals = @user.animals
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :edit
    end
  end

  private
  def user_find
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:comments, :email, :image)
  end

  def move_to_index
    redirect_to root_path if current_user.id != @user.id
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/edit.html.erb
<%= render "shared/second-header" %>

<div class="input-form">
  <div class="input-form-tittle">
    <h1 class="tittle-word">投稿編集画面</h1>
  </div>

  <br>

  <%= form_with model: @animal, url: animal_path, id: 'new-animal', class: 'new-animal', local: true do |f| %>
    <%# エラ〜メッセージ %>
    <%# <%= render "users/shared/error_messages", resource: resource %>
    <div class='form-wrap'>
        <div class='form-header'>
        <h1 class='form-header-text'>猫の情報入力</h1>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>性別</label>
          <span class='indispensable'>必須</span>
        </div>
          <%= f.radio_button :sex, :雄♂, cheched: true %>
          <%= f.label :sex, "雄♂", {value: :雄♂, style: "display: inline-block;"} %>
          <%= f.radio_button :sex, :雌♀ %>
          <%= f.label :sex, "雌♀", {value: :雌♀, style: "display: inline-block;"} %>
          <%= f.radio_button :sex, :不明 %>
          <%= f.label :sex, "不明", {value: :不明, style: "display: inline-block;"} %>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>推定年齢</label>
          <span class='indispensable'>必須</span>
        </div>
        <div class='cat-old'>
          <div class='cat-old-year'>
            <%= f.label :old_year_id, "〇〇才" %>
            <%= f.collection_select :old_year_id, OldYear.all, :id, :name, {} %>
          </div>
          <div class='cat-old-month'>
            <%= f.label :old_month, "〇〇ヶ月" %>
            <%= f.collection_select :old_month_id, OldMonth.all, :id, :name, {} %>
          </div>
        </div>
        
        <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>ワクチン接種</label>
          <span class='indispensable'>必須</span>
        </div>
          <%= f.radio_button :vaccine, :未, cheched: true %>
          <%= f.label :sex, "未", {value: :未, style: "display: inline-block;"} %>
          <%= f.radio_button :vaccine, :済 %>
          <%= f.label :sex, "済", {value: :済, style: "display: inline-block;"} %>
        </div>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>避妊/去勢手術</label>
          <span class='indispensable'>必須</span>
        </div>
          <%= f.radio_button :sterilization, :未, cheched: true %>
          <%= f.label :sex, "未", {value: :未, style: "display: inline-block;"} %>
          <%= f.radio_button :sterilization, :済 %>
          <%= f.label :sex, "済", {value: :済, style: "display: inline-block;"} %>
        </div>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">特徴（性格など）</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :character, class:"input-default", id:"character", placeholder:"例）人懐こく、呼んであげると寄ってきて膝の上に乗ります。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">譲渡費用（医療費・交通費など）</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :transfer_cost, class:"input-default", id:"transfer_cost", placeholder:"例）去勢手術費用が〇〇円でしたので、ご負担をお願いします。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">その他（譲渡条件など）</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :transfer_terms, class:"input-default", id:"transfer_terms", placeholder:"例）大切に育ててくれると約束してくれる方のみ応募お願いします。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">猫画像</label>
          <span class='indispensable'>必須</span>
        </div>
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :image, class: 'hidden' %>
      </div>

      <br>

      <div class="post-btn">
        <%= f.submit "更新", class:'signup-green-btn' %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to "topページに戻る", "/" %>

app/views/animals/index.html.erb
<%= render "shared/header" %>

<div class="wrapper">

  <div class="main">
    <div class="main-view">
      <div class="test-form">
        <p>・アプリ紹介文記載予定</p>
      </div>
      <div class="main-images">
        <div class="main-image1">
          <%= image_tag 'post.animal.png', class: 'image' %>
        </div>
        <div class="main-image2">
          <%= image_tag 'find.animal.png', class: 'image' %>
        </div>
      </div>
      <br>
      <div class="contents row">
        <h1>（仮）一覧表示</h1>
        <div class= "post-animals">
          <% @animals.each do |animal| %>
            <div class="post-animal">
              <%= link_to animal_path(animal.id) do %>
                  <%= image_tag animal.image.variant(resize: '250x250'), class: 'animal-image' if animal.image.attached? %>
              <% end %>
              <div class="animal-profile">
                <div class="animal-simple-prifile">
                  <p><%= animal.nickname %></p>
                  <p><%= "推定#{animal.old_year.name}#{animal.old_month.name}" %></p>
                  <p><%= animal.sex %></p>
                  <p><%= animal.prefecture.name %></p>
                  <%= link_to user_path(animal.user.id) do%>
                    <p><%= "投稿者 #{animal.user.nickname}さん" %></p>
                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <br>
      <p>・里親決定済画像一覧表示（日付新しい順３枚スライド表示）</p>
    </div>
  </div>

  <%= link_to(new_animal_path, class: 'family-btn') do %>
    <%= image_tag 'icon2.png', size:'170x70', class: "family-btn-icon" %>
    <span class='family-btn-text'>投稿する</span>
  <% end %>

</div>

<%= render "shared/footer" %>

app/views/animals/index_all.html.erb
test
<%= link_to "topへ", root_path %>

app/views/animals/new.html.erb
<%= render "shared/second-header" %>

<div class="input-form">
  <div class="input-form-tittle">
    <h1 class="tittle-word">新規投稿画面</h1>
  </div>

  <br>

  <%= form_with model: @animal, url: animals_path, id: 'new-animal', class: 'new-animal', local: true do |f| %>
    <%# エラ〜メッセージ %>
    <%# <%= render "users/shared/error_messages", resource: resource %>
    <div class='form-wrap'>
        <div class='form-header'>
        <h1 class='form-header-text'>猫の情報入力</h1>
      </div>

      <br>

      <div class="form-group">
        <div class="form-text-wrap">
          <label class='form-text'>ニックネーム・呼び名</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_field :nickname, class:"input-default", id:"nickname", placeholder:"例）白猫ちゃん", size: 40 %>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>性別</label>
          <span class='indispensable'>必須</span>
        </div>
          <%= f.radio_button :sex, :雄♂, cheched: true %>
          <%= f.label :sex, "雄♂", {value: :雄♂, style: "display: inline-block;"} %>
          <%= f.radio_button :sex, :雌♀ %>
          <%= f.label :sex, "雌♀", {value: :雌♀, style: "display: inline-block;"} %>
          <%= f.radio_button :sex, :不明 %>
          <%= f.label :sex, "不明", {value: :不明, style: "display: inline-block;"} %>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>推定年齢</label>
          <span class='indispensable'>必須</span>
        </div>
        <div class='cat-old'>
          <div class='cat-old-year'>
            <%= f.label :old_year_id, "〇〇才" %>
            <%= f.collection_select :old_year_id, OldYear.all, :id, :name, {} %>
          </div>
          <div class='cat-old-month'>
            <%= f.label :old_month, "〇〇ヶ月" %>
            <%= f.collection_select :old_month_id, OldMonth.all, :id, :name, {} %>
          </div>
        </div>
        
        <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>ワクチン接種</label>
          <span class='indispensable'>必須</span>
        </div>
          <%= f.radio_button :vaccine, :未, cheched: true %>
          <%= f.label :sex, "未", {value: :未, style: "display: inline-block;"} %>
          <%= f.radio_button :vaccine, :済 %>
          <%= f.label :sex, "済", {value: :済, style: "display: inline-block;"} %>
        </div>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>避妊/去勢手術</label>
          <span class='indispensable'>必須</span>
        </div>
          <%= f.radio_button :sterilization, :未, cheched: true %>
          <%= f.label :sex, "未", {value: :未, style: "display: inline-block;"} %>
          <%= f.radio_button :sterilization, :済 %>
          <%= f.label :sex, "済", {value: :済, style: "display: inline-block;"} %>
        </div>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">特徴（性格など）</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :character, class:"input-default", id:"character", placeholder:"例）人懐こく、呼んであげると寄ってきて膝の上に乗ります。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">里親を募集する理由</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :reason, class:"input-default", id:"reason", placeholder:"例）はぐれていたのか一匹でいるところを見つけ保護しました。住まいがペット不可の為、飼う事ができないので里親を探しています。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class='form-group'>
        <div class='form-text-wrap'>
          <label class='form-text'>猫がいる地域</label>
          <span class='indispensable'>必須</span>
        </div>
        <div class='living-area'>
          <%= f.label :prefecture_id, "都道府県" %>
          <%= f.collection_select :prefecture_id, Prefecture.all, :id, :name, {} %>
        </div>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">譲渡費用（医療費・交通費など）</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :transfer_cost, class:"input-default", id:"transfer_cost", placeholder:"例）去勢手術費用が〇〇円でしたので、ご負担をお願いします。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">その他（譲渡条件など）</label>
          <span class='indispensable'>必須</span>
        </div>
        <%= f.text_area :transfer_terms, class:"input-default", id:"transfer_terms", placeholder:"例）大切に育ててくれると約束してくれる方のみ応募お願いします。", size: "40x5", maxlength: 500,autofocus: true %>
      </div>

      <br>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">猫画像</label>
          <span class='indispensable'>必須</span>
        </div>
        <p>クリックしてファイルをアップロード</p>
        <%= f.file_field :image, class: 'hidden' %>
      </div>

      <br>

      <div class="post-btn">
        <%= f.submit "投稿", class:'signup-green-btn' %>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'トップページに戻る', "/" %>

app/views/animals/show.html.erb
<%= render "shared/second-header" %>

<div class="animal-information">
  <div class="animal-profile-tittle">
    <%# パンクズリスト入れたい %>
    <div class="animal-contents">
      <% if @animal.sex == "雄♂" %>
        <%= "#{@animal.nickname}くん" %>
      <% else %>
        <%= "#{@animal.nickname}ちゃん" %>
      <% end %>
    </div>
  </div>

  <div class="animal-profile-image">
    <div class="animal-item">
      <h1>【 画像 】</h1>
    </div>
    <div class="animal-contents">
      <%= image_tag @animal.image.variant(resize: '250x250'), class: 'animal-image' if @animal.image.attached? %>
    </div>
  </div>

  <div class="animal-sex">
    <div class="animal-item">
      <h1>【 性別 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.sex %>
    </div>
  </div>
  <div class="animal-old">
    <div class="animal-item">
      <h1>【 年齢 】</h1>
    </div>
    <div class="animal-contents">
      <%= "推定#{@animal.old_year.name}#{@animal.old_month.name}" %>
    </div>
  </div>
  <div class="animal-prefecture">
    <div class="animal-item">
      <h1>【 住んでいる地域 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.prefecture.name %>
    </div>
  </div>
  <div class="animal-vaccine">
    <div class="animal-item">
      <h1>【 ワクチンの接種 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.vaccine %>
    </div>
  </div>
  <div class="animal-sterilization">
    <div class="animal-item">
      <h1>【 去勢手術 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.sterilization %>
    </div>
  </div>
  <div class="animal-character">
    <div class="animal-item">
      <h1>【 特徴（性格など） 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.character %>
    </div>
  </div>
  <div class="animal-reason">
    <div class="animal-item">
      <h1>【 里親募集する理由 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.reason %>
    </div>
  </div>
  <div class="animal-transfer_cost">
    <div class="animal-item">
      <h1>【 譲渡費用（医療費、交通費など） 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.transfer_cost %>
    </div>
  </div>
  <div class="animal-transfer_terms">
    <div class="animal-item">
      <h1>【 その他（譲渡条件など） 】</h1>
    </div>
    <div class="animal-contents">
      <%= @animal.transfer_terms %>
    </div>
  </div>
</div>

<%# <br> %>
<%# ボタンで里親申込(チャットルームに遷移) %>
<br>

<div class="user-introduce">
  <div class="where-from">
    <h1>掲載者</h1>
  </div>
</div>
<div class="user-profile-box">
  <div class="left-box">
    <div class="user-picture">
    </div>
  </div>
  <div class="rigth-box">
    <div class="user-nickname">
      <%= "掲載者： #{@animal.user.nickname}" %>
    </div>
    <div class="user-gender">
      <% "性別： #{@animal.user.gender}" %>
    </div>
    <div class="user-old">
      <%= "年代: #{@animal.user.old.name}" %>
    </div>
    <div class="user-prefecture">
      <%= "所属県: #{@animal.user.prefecture.name}" %>
    </div>
  </div>
  <div class="under-box">
    <div class="show-profile">
      <%= link_to "プロフィールを見る", user_path(@animal.user.id), method: :get, class: 'btn' %>
    </div>
  </div>
</div>

<br>

<% if user_signed_in? %>
  <% if current_user.id == @animal.user.id %>
    <div class="edit-delete-btn">
      <div class="edit-btn">
        <%# ボタン表示 %>
        <%= link_to "編集", edit_animal_path, method: :get, class: 'btn' %>
      </div>
      <div class="delete-btn">
        <%# ボタン表示 %>
        <%= link_to "削除", animal_path, method: :delete, class: 'btn' %>
      </div>
    </div>
  <% end %>
<% end %>

<br>

<%= link_to "topページに戻る", "/" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalMatchingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <h1>より多くの家族と出会えますように</h1>
</div>

app/views/shared/_header.html.erb
<div class="header">
  <div class="left-box">
    <%= image_tag "index-tittle-logo.png", class: "image" %>
  </div>
  <div class="right-box">
  <%# 以下リンクにするかボタンにするか悩み中（現在リンク（仮）） %>
  <%# 投稿ボタンを画面右下固定にするか悩み中 %>
    <% if user_signed_in? %>
      <%= link_to "#{current_user.nickname}", user_path(current_user.id), method: :get, class: 'btn' %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
      <%# ログアウト実装後投稿ボタンに変更 %>
    <% else %>
        <%= link_to "会員登録", new_user_registration_path, class: 'btn' %>
        <%= link_to "ログイン", new_user_session_path, method: :get, class: 'btn' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= render "shared/second-header" %>

<div class="user-information">
  <div class="user-profile-tittle">
    <%# パンクズリスト入れたい %>
    <div class="user-contents">
      <%= "#{@user.nickname}さんのプロフィール" %>
    </div>
  </div>

  <div class="user-gender">
    <div class="user-item">
      <h1>【 プロフィール画像 】</h1>
    </div>
    <div class="user-contents">
      <%= image_tag @user.image.variant(resize: '250x250'), class: 'user-image' if @user.image.attached? %>
    </div>
    <div class="user-item">
      <h1>【 性別 】</h1>
    </div>
    <div class="user-contents">
      <%= @user.gender %>
    </div>
  </div>
  <div class="user-old">
    <div class="user-item">
      <h1>【 年齢 】</h1>
    </div>
    <div class="user-contents">
      <%= @user.old.name %>
    </div>
  </div>
  <div class="user-prefecture">
    <div class="user-item">
      <h1>【 都道府県 】</h1>
    </div>
    <div class="user-contents">
      <%= @user.prefecture.name %>
    </div>
  </div>
  <div class="user-comment">
    <div class="user-item">
      <h1>【 自己紹介・活動内容など 】</h1>
    </div>
    <div class="user-contents">
    <%# BOX内でenterを押すと改行。表示も改行して見えるように%>
      <%= @user.comments %>
    </div>
  </div>
  <div class="user-animals">
    <div class="user-item">
      <%= "#{@user.nickname}さんの投稿一覧" %>
    </div>
    <div class="user-contents">
      <% @animals.each do |animal| %>
        <%= link_to animal_path(animal.id) do %>
          <div class="user-animals">
            <div class="animals-picture">
              <%= image_tag animal.image.variant(resize: '250x250'), class: 'animal-image' if animal.image.attached? %>
            </div>
            <div class="animal-name-sex">
              <%= "#{animal.nickname} #{animal.sex}" %>
            </div>
        <% end %>
      <%end%>
    </div>
  </div>
</div>

<br>

<% if user_signed_in? %>
  <% if @user.id == current_user.id %>
    <div class="edit-btn">
      <%# ボタン表示 %>
      <%= link_to "編集", edit_user_path, method: :get, class: 'btn' %>
    </div>
  <% end %>
<% end %>

<br>
<%= link_to "トップページに戻る", "/" %>